services:
  db:
    image: postgres:latest
    container_name: LogiTrack_DW
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "admin123"
      POSTGRES_DB: logitrack_dw
    ports:
      - "5433:5432"
    volumes:
      - ./data_db:/var/lib/postgresql
  adminer:
    image: adminer:latest
    container_name: LogiTrack_Adminer
    restart: always
    ports:
      - "8080:8080"
